djangoCRM/urls.py
from django.contrib import admin
from django.urls import path, include
from leads.views import homePage, HomePageView, SignUpView, DashboardView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import (
    LoginView, 
    LogoutView, 
    PasswordResetView, 
    PasswordResetDoneView, 
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', homePage, name='homePage'),
    path('', HomePageView.as_view(), name='homePage'),
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    path("leads/",include('leads.urls', namespace="leads")),
    path("agents/",include('agents.urls', namespace="agents")),
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("signup/", SignUpView.as_view(), name="signup"),
    path("resetPassword/", PasswordResetView.as_view(), name="resetPassword"),
    path("resetPasswordDone/", PasswordResetDoneView.as_view(), name="password_reset_done"),
    path("resetPasswordConfirm/<uidb64>/<token>/", PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path("resetPasswordComplete/", PasswordResetCompleteView.as_view(), name="password_reset_complete"),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

leads/urls.py
from django.urls import path
from .views import (
    leadListView, 
    leadDetailView, 
    createLeadView,
    updateLeadView, 
    deleteLeadView, 
    AssignAgentView,
    CategoryListView,
    CategoryDetailView, 
    UpdateCategoryView,
    FollowUpCreateView,
    FollowUpUpdateView,
    FollowUpDeleteView,
    LeadJsonView,
    LeadCategoryUpdateView,
    CategoryDeleteView,
    CategoryCreateView
)

app_name="leads"

urlpatterns = [
    path("", leadListView.as_view(), name='leadList'),
    path("create/", createLeadView.as_view(), name='createLead'),
    path("<int:pk>/", leadDetailView.as_view(), name='leadDetail'),
    path("<int:pk>/update/", updateLeadView.as_view(), name='updateLead'),
    path("<int:pk>/delete/", deleteLeadView.as_view(), name='deleteLead'),
    path("<int:pk>/assignAgent/", AssignAgentView.as_view(), name='assignAgent'),
    path("categories/", CategoryListView.as_view(), name="categoryList"),
    path("categoryDetail/<int:pk>/", CategoryDetailView.as_view(), name="categoryDetail"),
    path("<int:pk>/updateCategory/", LeadCategoryUpdateView.as_view(), name='updateLeadCategory'),
    
    path('json/', LeadJsonView.as_view(), name='lead-list-json'),
    path('<int:pk>/followups/create/', FollowUpCreateView.as_view(), name='createLeadFollowup'),
    path('followups/<int:pk>/', FollowUpUpdateView.as_view(), name='lead-followup-update'),
    path('followups/<int:pk>/delete/', FollowUpDeleteView.as_view(), name='lead-followup-delete'),
    path('categories/<int:pk>/update/', UpdateCategoryView.as_view(), name='categoryUpdate'),
    path('categories/<int:pk>/delete/', CategoryDeleteView.as_view(), name='categoryDelete'),
    path('createCategory/', CategoryCreateView.as_view(), name='categoryCreate'),
]

leads/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models.signals import post_save

# Create your models here.

class User(AbstractUser):
    is_organisor = models.BooleanField(default=True)
    is_agent = models.BooleanField(default=False)


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username


class LeadManager(models.Manager):

    def get_queryset(self):
        return super().get_queryset()


class Lead(models.Model):
    firstName = models.CharField(max_length=20, default="", null=True, blank=True)
    lastName = models.CharField(max_length=20, default="", null=True, blank=True)
    age = models.IntegerField(default=0, null=True, blank=True)
    agent = models.ForeignKey("Agent", null=True, blank=True, on_delete=models.SET_NULL)
    organisation = models.ForeignKey("UserProfile", on_delete=models.CASCADE)
    category = models.ForeignKey("Category", related_name="leads", null=True, blank=True, on_delete=models.SET_NULL)
    description = models.TextField()
    dateAdded = models.DateTimeField(auto_now_add = True)
    phoneNumber = models.CharField(max_length=20)
    email = models.EmailField()
    profile_picture = models.ImageField(null=True, blank=True, upload_to="profile_pictures/")
    converted_date = models.DateTimeField(null=True, blank=True)

    objects = LeadManager()

    def __str__(self):
        return f"{self.firstName} {self.lastName}"    


def handle_upload_follow_ups(instance, filename):
    return f"lead_followups/lead_{instance.lead.pk}/{filename}"


class FollowUp(models.Model):
    lead = models.ForeignKey(Lead, related_name="followups", on_delete=models.CASCADE)
    date_added = models.DateTimeField(auto_now_add=True)
    notes = models.TextField(blank=True, null=True)
    file = models.FileField(null=True, blank=True, upload_to=handle_upload_follow_ups)

    def __str__(self):
        return f"{self.lead.firstName} {self.lead.lastName}"


class Agent(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    organisation = models.ForeignKey("UserProfile", on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username



class Category(models.Model):
    name = models.CharField(max_length=30)
    organisation = models.ForeignKey("UserProfile", on_delete=models.CASCADE)

    def __str__(self):
        return self.name


# Signals
def postUserCreatedSignal(sender, instance, created, **kwargs):
    print(instance, created)
    if created:
        UserProfile.objects.create(user=instance)


post_save.connect(postUserCreatedSignal, sender=User) 

leads/forms.py
from django import forms
from .models import Lead, Agent, Category, FollowUp
from django.contrib.auth.forms import UserCreationForm, UsernameField
from django.contrib.auth import get_user_model


User = get_user_model()

class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = User
        fields = ("username",)
        field_classes = {'username': UsernameField}


class LeadForm(forms.Form):
    firstName = forms.CharField()
    lastName = forms.CharField()
    age = forms.IntegerField(min_value=0)


class LeadModelForm(forms.ModelForm):
    class Meta:
        model = Lead
        fields = (
            'firstName','lastName','age','agent', 'description', 'phoneNumber','email','profile_picture'
        )


class AssignAgentForm(forms.Form):
    agent = forms.ModelChoiceField(queryset=Agent.objects.none())

    def __init__(self, *args, **kwargs):
        request = kwargs.pop("request")
        print(request.user)
        agents = Agent.objects.filter(organisation = request.user.userprofile)
        super(AssignAgentForm, self).__init__(*args, **kwargs)
        self.fields["agent"].queryset = agents


class LeadCategoryUpdateForm(forms.ModelForm):
    class Meta:
        model = Lead
        fields = (
            'category',
        )


class CategoryModelForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = (
            'name',
        )


class FollowUpModelForm(forms.ModelForm):
    class Meta:
        model = FollowUp
        fields = (
            'notes',
            'file'
        )

leads/views.py
import datetime
import logging
from django import contrib
from django.contrib import messages
from django.shortcuts import render, redirect, reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from django.http.response import JsonResponse
from .models import Lead, Agent, Category, FollowUp
from .forms import (LeadForm, LeadModelForm, CustomUserCreationForm, AssignAgentForm, LeadCategoryUpdateForm, CategoryModelForm, FollowUpModelForm)
from django.views.generic import (TemplateView, ListView, DetailView,CreateView, UpdateView, DeleteView, FormView, View)
from django.core.mail import send_mail
from agents.mixins import OrganisorAndLoginRequiredMixin

# Create your views here.

logger = logging.getLogger(__name__)


class SignUpView(CreateView):
    template_name = "registration/signUp.html"
    form_class = CustomUserCreationForm
    
    def get_success_url(self):
        return reverse("login")


class HomePageView(TemplateView):
    template_name = "homePage.html"

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect("dashboard")
        return super().dispatch(request, *args, **kwargs)


def homePage(request):
    return render(request, "homePage.html")


class leadListView(LoginRequiredMixin, ListView):
    template_name = "leads/leadList.html"
    context_object_name = "leads" #Default name is object_list

    def get_queryset(self):
        user = self.request.user

        # Initial QuerySet of leads for entire organisation
        if user.is_organisor:
            queryset = Lead.objects.filter(organisation = user.userprofile, agent__isnull=False)
        else:
            queryset = Lead.objects.filter(organisation = user.agent.organisation, agent__isnull=False)   
            # Filter leads for current agent
            queryset = queryset.filter(agent__user = user)
        return queryset

    def get_context_data(self, **kwargs):
        user = self.request.user
        context = super(leadListView, self).get_context_data(**kwargs)
        if user.is_organisor:
            queryset = Lead.objects.filter(organisation = user.userprofile, agent__isnull=True)
            context.update({
                "unassignedLeads": queryset
            })
        return context


def leadList(request):
    leads = Lead.objects.all()
    context = {
        "leads" : leads
    }
    return render(request,"leads/leadList.html", context)


class leadDetailView(LoginRequiredMixin, DetailView):
    template_name = "leads/leadDetail.html"
    context_object_name = "lead" #Default name is object_list

    def get_queryset(self):
        user = self.request.user

        # Initial QuerySet of leads for entire organisation
        if user.is_organisor:
            queryset = Lead.objects.filter(organisation = user.userprofile)
        else:
            queryset = Lead.objects.filter(organisation = user.agent.organisation)   
            # Filter leads for current agent
            queryset = queryset.filter(agent__user = user)
        return queryset


def leadDetail(request, pk):
    print(pk)
    lead = Lead.objects.get(id=pk)
    print(lead)
    context = {
        "lead" : lead
    }
    return render(request,"leads/leadDetail.html", context)


class createLeadView(OrganisorAndLoginRequiredMixin, CreateView):
    template_name = "leads/createLead.html"
    form_class = LeadModelForm

    def get_success_url(self):
        return reverse("leads:leadList")

    def form_valid(self, form):
        lead = form.save(commit=False)
        lead.organisation = self.request.user.userprofile
        lead.save()
        send_mail(
            subject="A lead has been created",
            message="Go to the site to see the new lead",
            from_email="test@test.com",
            recipient_list=["test2@test.com"]
        )
        messages.success(self.request, "You have successfully created a lead")
        return super(createLeadView, self).form_valid(form)


def createLead(request):
    form = LeadModelForm()
    if(request.method == "POST"):
        print("POST Request")
        form = LeadModelForm(request.POST)
        if form.is_valid():
            # firstName = form.cleaned_data['firstName']
            # lastName = form.cleaned_data['lastName']
            # age = form.cleaned_data['age']
            # agent = form.cleaned_data['agent']
            # Lead.objects.create(
            #     firstName = firstName,
            #     lastName = lastName,
            #     age = age,
            #     agent = agent,
            # )
            form.save()
            return redirect("/leads")

    context = {
        "form": form
    }
    return render(request, "leads/createLead.html", context)


class updateLeadView(OrganisorAndLoginRequiredMixin, UpdateView):
    template_name = "leads/updateLead.html"
    form_class = LeadModelForm

    def get_success_url(self):
        return reverse("leads:leadList")

    def get_queryset(self):
        user = self.request.user
        # Initial QuerySet of leads for entire organisation
        return Lead.objects.filter(organisation = user.userprofile)

    def form_valid(self, form):
        form.save()
        messages.info(self.request, "You have successfully updated this lead")
        return super(updateLeadView, self).form_valid(form)


def updateLead(request, pk):
    lead = Lead.objects.get(id=pk)
    # form = LeadForm()
    form = LeadModelForm(instance=lead)
    if(request.method == "POST"):
        form = LeadModelForm(request.POST, instance=lead)
        if form.is_valid():
            # firstName = form.cleaned_data['firstName']
            # lastName = form.cleaned_data['lastName']
            # age = form.cleaned_data['age']
            # lead.firstName = firstName
            # lead.lastName = lastName
            # lead.age = age
            # lead.save()
            form.save()
            return redirect("/leads")

    context={ "lead":lead, "form": form }
    return render(request, "leads/updateLead.html", context)


class deleteLeadView(OrganisorAndLoginRequiredMixin, DeleteView):
    template_name = "leads/deleteLead.html"
    
    def get_queryset(self):
        user = self.request.user
        # Initial QuerySet of leads for entire organisation
        return Lead.objects.filter(organisation = user.userprofile)

    def get_success_url(self):
        return reverse("leads:leadList")


def deleteLead(request,pk):
    lead= Lead.objects.get(id=pk)
    lead.delete()
    return redirect("/leads")


class AssignAgentView(OrganisorAndLoginRequiredMixin, FormView):
    template_name = "leads/assignAgent.html"
    form_class = AssignAgentForm

    def get_form_kwargs(self, **kwargs):
        kwargs = super(AssignAgentView, self).get_form_kwargs(**kwargs)
        kwargs.update({
            "request": self.request
        })
        return kwargs

    def get_success_url(self):
        return reverse("leads:leadList")

    def form_valid(self, form):
        agent = form.cleaned_data["agent"]
        lead = Lead.objects.get(id = self.kwargs["pk"])
        lead.agent = agent
        lead.save()
        return super(AssignAgentView, self).form_valid(form)


class CategoryListView(LoginRequiredMixin, ListView):
    template_name = "leads/categoryList.html"
    context_object_name = "categoryList"

    def get_context_data(self, **kwargs):
        context = super(CategoryListView, self).get_context_data(**kwargs)
        user = self.request.user
        # Initial QuerySet of leads for entire organisation
        if user.is_organisor:
            queryset = Lead.objects.filter(organisation = user.userprofile)
        else:
            queryset = Lead.objects.filter(organisation = user.agent.organisation)   
        context.update({
            "unassignedLeadCount": queryset.filter(category__isnull = True).count()
        })
        return context
    
    def get_queryset(self):
        user = self.request.user
        # Initial QuerySet of leads for entire organisation
        if user.is_organisor:
            queryset = Category.objects.filter(organisation = user.userprofile)
        else:
            queryset = Category.objects.filter(organisation = user.agent.organisation)   
        return queryset


class CategoryDetailView(LoginRequiredMixin, DetailView):
    template_name = "leads/categoryDetail.html"
    context_object_name = "category"

    # def get_context_data(self, **kwargs):
    #     context = super(CategoryDetailView, self).get_context_data(**kwargs)
    #     queryset = Lead.objects.filter(category = self.get_object())
    #     queryset = self.get_object().lead_set.all()
    #     leads = self.get_object().leads.all()
    #     context.update({
    #         "leads" : leads
    #     })
    #     return context    

    def get_queryset(self):
        user = self.request.user
        # Initial QuerySet of leads for entire organisation
        if user.is_organisor:
            queryset = Category.objects.filter(organisation = user.userprofile)
        else:
            queryset = Category.objects.filter(organisation = user.agent.organisation)   
        return queryset


class CategoryCreateView(OrganisorAndLoginRequiredMixin, CreateView):
    template_name = "leads/createCategory.html"
    form_class = CategoryModelForm

    def get_success_url(self):
        return reverse("leads:categoryList")

    def form_valid(self, form):
        category = form.save(commit=False)
        category.organisation = self.request.user.userprofile
        category.save()
        return super(CategoryCreateView, self).form_valid(form)


class UpdateCategoryView(OrganisorAndLoginRequiredMixin, UpdateView):
    template_name = "leads/updateCategory.html"
    form_class = LeadCategoryUpdateForm

    def get_success_url(self):
        return reverse("leads:categoryList")

    def get_queryset(self):
        user = self.request.user

leads/templates/leads/categoryDetail.html
{% extends "base.html" %} {% block content %}

<section class="text-gray-600 body-font">
	<div class="container px-5 py-12 mx-auto">
		<div
			class="
				mb-6
				py-3
				flex
				justify-between
				items-center
				border-b border-gray-200
			"
		>
			<div>
				<h1 class="text-4xl text-gray-800">{{ category.name }}</h1>
				<p class="mx-auto leading-relaxed text-base">
					These are the leads under this category.
				</p>
			</div>

			<div>
				<a
					class="text-gray-500 hover:text-blue-500 mr-5"
					href="{% url 'leads:categoryUpdate' category.pk %}"
					>Update Category</a
				>
				<a
					class="text-gray-500 hover:text-blue-500"
					href="{% url 'leads:categoryDelete' category.pk %}"
					>Delete Category</a
				>
			</div>
		</div>
		<div class="lg:w-2/3 w-full mx-auto overflow-auto">
			<table class="table-auto w-full text-left whitespace-no-wrap">
				<thead>
					<tr>
						<th
							class="
								px-4
								py-3
								title-font
								tracking-wider
								font-medium
								text-gray-900 text-sm
								bg-gray-100
								rounded-tl rounded-bl
							"
						>
							First Name
						</th>
						<th
							class="
								px-4
								py-3
								title-font
								tracking-wider
								font-medium
								text-gray-900 text-sm
								bg-gray-100
							"
						>
							Last Name
						</th>
					</tr>
				</thead>
				<tbody>
					{% for lead in category.leads.all %}
					<tr>
						<td class="px-4 py-3 border-t-2 border-gray-200">
							<a
								class="hover:text-blue-500"
								href="{% url 'leads:leadDetail' lead.pk %}"
							>
								{{ lead.firstName }}</a
							>
						</td>
						<td class="px-4 py-3 border-t-2 border-gray-200">
							{{ lead.lastName }}
						</td>
					</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>
	</div>
</section>

{% endblock content %}

leads/templates/leads/leadCategoryUpdate.html
{% extends "base.html" %} {% load tailwind_filters %} {% block content %}

<section class="text-gray-600 body-font overflow-hidden">
	<div class="container px-5 py-8 mx-auto">
		<div class="mx-auto flex flex-wrap">
			<div class="w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
				<div class="border-b border-gray-300 mb-4 pb-2">
					<a
						class="hover:text-blue-500"
						href="{% url 'leads:leadList' %}"
						>Go Back to Leads</a
					>
				</div>
				<h2 class="text-sm title-font text-gray-500 tracking-widest">
					Lead
				</h2>
				<h1 class="text-gray-900 text-3xl title-font font-medium mb-4">
					{{lead.firstName}} {{lead.lastName}}
				</h1>
				<div class="flex mb-4">
					<a
						href="{% url 'leads:leadDetail' lead.pk %}"
						class="
							flex-grow
							border-b-2 border-gray-300
							py-2
							text-lg
							px-1
						"
						>Description</a
					>
					<a
						href="{% url 'leads:updateLead' lead.pk %}"
						class="
							flex-grow
							border-b-2 border-gray-300
							py-2
							text-lg
							px-1
						"
						>Update Details</a
					>
					<a
						href="{% url 'leads:updateLeadCategory' lead.pk %}"
						class="
							flex-grow
							text-indigo-500
							border-b-2 border-indigo-500
							py-2
							text-lg
							px-1
						"
						>Update Category</a
					>
				</div>
				<form action="." method="POST">
					{% csrf_token %} {{ form|crispy}}
					<button
						class="
							w-full
							bg-blue-500
							text-white
							hover:bg-blue-600
							px-3
							py-2
							rounded-md
						"
						type="submit"
					>
						Update Category
					</button>
				</form>
			</div>
		</div>
	</div>
</section>

{% endblock content %}

leads/templates/leads/leadDetail.html
{% extends "base.html" %} {% block content %}

<section class="text-gray-600 body-font overflow-hidden">
	<div class="container px-5 py-4 mx-auto">
		<div class="mx-auto flex flex-wrap">
			<div class="w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
				<div class="w-full flex items-center justify-between space-x-6">
					<div class="flex-1 truncate">
						<div class="border-b border-gray-300 mb-2 pb-2">
							<a
								class="hover:text-blue-500"
								href="{% url 'leads:leadList' %}"
								>Go Back to Leads</a
							>
						</div>
						<h2
							class="
								text-sm
								title-font
								text-gray-500
								tracking-widest
							"
						>
							Lead
						</h2>
						<div class="flex items-center space-x-3">
							<h3
								class="
									text-3xl text-gray-900
									font-medium
									truncate
								"
							>
								{{ lead.firstName }} {{ lead.lastName }}
							</h3>
						</div>
						<p class="mt-1 text-lg text-gray-800 truncate">
							{{ lead.description }}
						</p>
					</div>
					{% if lead.profile_picture %}
					<img
						class="w-10 h-10 bg-gray-300 rounded-full flex-shrink-0"
						src="{{ lead.profile_picture.url }}"
						alt=""
					/>
					{% endif %}
				</div>
				<div class="flex mb-4">
					<a
						href="{% url 'leads:leadDetail' lead.pk %}"
						class="
							flex-grow
							text-indigo-500
							border-b-2 border-indigo-500
							py-2
							text-lg
							px-1
						"
						>Description</a
					>
					<a
						href="{% url 'leads:updateLead' lead.pk %}"
						class="
							flex-grow
							border-b-2 border-gray-300
							py-2
							text-lg
							px-1
						"
						>Update Details</a
					>
					<a
						href="{% url 'leads:updateLeadCategory' lead.pk %}"
						class="
							flex-grow
							border-b-2 border-gray-300
							py-2
							text-lg
							px-1
						"
						>Update Category</a
					>
				</div>
				<div class="flex border-t border-gray-300 py-2">
					<span class="text-gray-500">Age</span>
					<span class="ml-auto text-gray-900">{{ lead.age }}</span>
				</div>
				<div class="flex border-t border-gray-300 py-2">
					<span class="text-gray-500">Email</span>
					<span class="ml-auto text-gray-900">{{ lead.email }}</span>
				</div>
				<div class="flex border-t border-b mb-6 border-gray-300 py-2">
					<span class="text-gray-500">Phone Number</span>
					<span class="ml-auto text-gray-900"
						>{{ lead.phoneNumber }}</span
					>
				</div>
			</div>

			<a
				href="{% url 'leads:createLeadFollowup' lead.pk %}"
				class="
					text-white
					bg-blue-700
					hover:bg-blue-600
					px-5
					py-2
					rounded-md
				"
				>Create a FollowUp</a
			>
		</div>
		{% for followup in lead.followups.all %}
		<div class="mt-5 shadow px-4 sm:px-6">
			<div class="pt-4 sm:py-4 sm:grid sm:grid-cols-3 sm:gap-4">
				<dt class="text-sm font-medium text-gray-500">
					Notes (<a
						href="{% url 'leads:lead-followup-update' followup.pk %}"
						class="text-blue-500 hover:text-blue-700"
						>update</a
					>)
				</dt>
				<dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
					{{ followup.notes }}
				</dd>
			</div>
			{% if followup.file %}
			<div class="py-2 sm:py-4 sm:grid sm:grid-cols-3 sm:gap-4">
				<dt class="text-sm font-medium text-gray-500">Attachments</dt>
				<dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
					<ul
						class="
							border border-gray-200
							rounded-md
							divide-y divide-gray-200
						"
					>
						<li
							class="
								pl-3
								pr-4
								py-3
								flex
								items-center
								justify-between
								text-sm
							"
						>
							<div class="w-0 flex-1 flex items-center">
								<!-- Heroicon name: paper-clip -->
								<svg
									class="flex-shrink-0 h-5 w-5 text-gray-400"
									xmlns="http://www.w3.org/2000/svg"
									viewBox="0 0 20 20"
									fill="currentColor"
									aria-hidden="true"
								>
									<path
										fill-rule="evenodd"
										d="M8 4a3 3 0 00-3 3v4a5 5 0 0010 0V7a1 1 0 112 0v4a7 7 0 11-14 0V7a5 5 0 0110 0v4a3 3 0 11-6 0V7a1 1 0 012 0v4a1 1 0 102 0V7a3 3 0 00-3-3z"
										clip-rule="evenodd"
									/>
								</svg>
								<span class="ml-2 flex-1 w-0 truncate">
									{{ followup.file.name }}
								</span>
							</div>
							<div class="ml-4 flex-shrink-0">
								<a
									href="{{ followup.file.url }}"
									download
									class="
										font-medium
										text-indigo-600
										hover:text-indigo-500
									"
								>
									Download
								</a>
							</div>
						</li>
					</ul>
				</dd>
			</div>
			{% endif %}
		</div>
		{% endfor %}
	</div>
</section>

{% endblock content %}

leads/templates/leads/updateLead.html
{% extends "base.html" %} {% load tailwind_filters %} {% block content %}

<section class="text-gray-600 body-font overflow-hidden">
	<div class="container px-5 py-8 mx-auto">
		<div class="mx-auto flex flex-wrap">
			<div class="w-full lg:pr-10 lg:pb-6 mb-6 lg:mb-0">
				<div class="border-b border-gray-300 mb-2 pb-2">
					<a
						class="hover:text-blue-500"
						href="{% url 'leads:leadList' %}"
						>Go Back to Leads</a
					>
				</div>
				<h2 class="text-sm title-font text-gray-500 tracking-widest">
					Lead
				</h2>
				<h1 class="text-gray-900 text-3xl title-font font-medium">
					{{lead.firstName}} {{lead.lastName}}
				</h1>
				<div class="flex mb-4">
					<a
						href="{% url 'leads:leadDetail' lead.pk %}"
						class="
							flex-grow
							border-b-2 border-gray-300
							py-2
							text-lg
							px-1
						"
						>Description</a
					>
					<a
						href="{% url 'leads:updateLead' lead.pk %}"
						class="
							flex-grow
							text-indigo-500
							border-b-2 border-indigo-500
							py-2
							text-lg
							px-1
						"
						>Update Details</a
					>
					<a
						href="{% url 'leads:updateLeadCategory' lead.pk %}"
						class="
							flex-grow
							border-b-2 border-gray-300
							py-2
							text-lg
							px-1
						"
						>Update Category</a
					>
				</div>
				<form action="." method="POST">
					{% csrf_token %} {{ form|crispy}}
					<button
						class="
							w-full
							bg-blue-500
							text-white
							hover:bg-blue-600
							px-3
							py-2
							rounded-md
						"
						type="submit"
					>
						Update Details
					</button>
				</form>
				<div class="mt-5 py-5 border-t border-gray-200">
					<a
						href="{% url 'leads:deleteLead' lead.pk %}"
						class="
							w-1/2
							mt-3
							text-white
							bg-indigo-500
							border-0
							py-2
							px-6
							focus:outline-none
							hover:bg-indigo-600
							rounded
						"
					>
						Delete Lead
					</a>
				</div>
			</div>
		</div>
	</div>
</section>

{% endblock content %}