agents/urls.py
from django.urls import path
from .views import AgentListView, CreateAgentView, AgentDetailView, UpdateAgentView, AgentDeleteView

app_name="agents"

urlpatterns = [
    path("", AgentListView.as_view(), name='agentList'),
    path("create/", CreateAgentView.as_view(), name='createAgent'),
    path("<int:pk>/", AgentDetailView.as_view(), name='agentDetail'),
    path("<int:pk>/update/", UpdateAgentView.as_view(), name='updateAgent'),
    path("<int:pk>/delete/", AgentDeleteView.as_view(), name='deleteAgent')
]

djangoCRM/urls.py
from django.contrib import admin
from django.urls import path, include
from leads.views import homePage, HomePageView, SignUpView, DashboardView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import (
    LoginView, 
    LogoutView, 
    PasswordResetView, 
    PasswordResetDoneView, 
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', homePage, name='homePage'),
    path('', HomePageView.as_view(), name='homePage'),
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    path("leads/",include('leads.urls', namespace="leads")),
    path("agents/",include('agents.urls', namespace="agents")),
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("signup/", SignUpView.as_view(), name="signup"),
    path("resetPassword/", PasswordResetView.as_view(), name="resetPassword"),
    path("resetPasswordDone/", PasswordResetDoneView.as_view(), name="password_reset_done"),
    path("resetPasswordConfirm/<uidb64>/<token>/", PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path("resetPasswordComplete/", PasswordResetCompleteView.as_view(), name="password_reset_complete"),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

leads/urls.py
from django.urls import path
from .views import (
    leadListView, 
    leadDetailView, 
    createLeadView,
    updateLeadView, 
    deleteLeadView, 
    AssignAgentView,
    CategoryListView,
    CategoryDetailView, 
    UpdateCategoryView,
    FollowUpCreateView,
    FollowUpUpdateView,
    FollowUpDeleteView,
    LeadJsonView,
    LeadCategoryUpdateView,
    CategoryDeleteView,
    CategoryCreateView
)

app_name="leads"

urlpatterns = [
    path("", leadListView.as_view(), name='leadList'),
    path("create/", createLeadView.as_view(), name='createLead'),
    path("<int:pk>/", leadDetailView.as_view(), name='leadDetail'),
    path("<int:pk>/update/", updateLeadView.as_view(), name='updateLead'),
    path("<int:pk>/delete/", deleteLeadView.as_view(), name='deleteLead'),
    path("<int:pk>/assignAgent/", AssignAgentView.as_view(), name='assignAgent'),
    path("categories/", CategoryListView.as_view(), name="categoryList"),
    path("categoryDetail/<int:pk>/", CategoryDetailView.as_view(), name="categoryDetail"),
    path("<int:pk>/updateCategory/", LeadCategoryUpdateView.as_view(), name='updateLeadCategory'),
    
    path('json/', LeadJsonView.as_view(), name='lead-list-json'),
    path('<int:pk>/followups/create/', FollowUpCreateView.as_view(), name='createLeadFollowup'),
    path('followups/<int:pk>/', FollowUpUpdateView.as_view(), name='lead-followup-update'),
    path('followups/<int:pk>/delete/', FollowUpDeleteView.as_view(), name='lead-followup-delete'),
    path('categories/<int:pk>/update/', UpdateCategoryView.as_view(), name='categoryUpdate'),
    path('categories/<int:pk>/delete/', CategoryDeleteView.as_view(), name='categoryDelete'),
    path('createCategory/', CategoryCreateView.as_view(), name='categoryCreate'),
]

agents/models.py
from django.db import models

# Create your models here.

agents/forms.py
from django import forms
from django.contrib.auth import get_user_model

User = get_user_model()

class AgentModelForm(forms.ModelForm):
    class Meta:
        model = User
        fields = (
            'email',
            'username',
            'first_name',
            'last_name',
        )

agents/views.py
from django.shortcuts import render, reverse
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from leads.models import Agent
from .forms import AgentModelForm
from .mixins import OrganisorAndLoginRequiredMixin
from django.core.mail import send_mail
import random

# Create your views here.

class AgentListView(OrganisorAndLoginRequiredMixin, generic.ListView):
    template_name = "agents/agentList.html"

    def get_queryset(self):
        organisation = self.request.user.userprofile
        return Agent.objects.filter(organisation = organisation)


class CreateAgentView(OrganisorAndLoginRequiredMixin, generic.CreateView):
    template_name = "agents/createAgent.html"
    form_class  = AgentModelForm

    def get_success_url(self):
        return reverse("agents:agentList")

    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_agent = True
        user.is_organisor = False
        user.set_password(f"{random.randint(0, 1000000)}")
        user.save()
        Agent.objects.create(
            user = user,
            organisation = self.request.user.userprofile
        )
        send_mail(
            subject = "You are invited to be an agent.",
            message = "You are added as an agent on CRM. Please come to login and start working.",
            from_email = "aakritigupta1435@gmail.com",
            recipient_list = [user.email]
        )
        return super(CreateAgentView, self).form_valid(form)


class UpdateAgentView(OrganisorAndLoginRequiredMixin, generic.UpdateView):
    template_name = "agents/updateAgent.html"
    form_class  = AgentModelForm

    def get_success_url(self):
        return reverse("agents:agentList")

    def get_queryset(self):
        organisation = self.request.user.userprofile
        return Agent.objects.filter(organisation = organisation)



class AgentDetailView(OrganisorAndLoginRequiredMixin, generic.DetailView):
    template_name = "agents/agentDetail.html"
    context_object_name = "agent"

    def get_queryset(self):
        organisation = self.request.user.userprofile
        return Agent.objects.filter(organisation = organisation)


class AgentDeleteView(OrganisorAndLoginRequiredMixin, generic.DeleteView):
    template_name = "agents/agentDelete.html"
    context_object_name = "agent"

    def get_queryset(self):
        organisation = self.request.user.userprofile
        return Agent.objects.filter(organisation = organisation)

    def get_success_url(self):
        return reverse("agents:agentList")

    

agents/templates/agents/agentDelete.html
{% extends "base.html" %} {% load tailwind_filters %} {% block content %}

<div class="max-w-lg mx-auto">
	<div class="pt-3 border-b border-gray-300 mt-2 mb-4 pb-2">
		<a class="hover:text-blue-500" href="{% url 'agents:agentList' %}"
			>Go Back to Agents</a
		>
	</div>
	<div class="pt-3 border-b border-gray-300 mt-2 mb-4 pb-2">
		<h1 class="text-xl">Are you sure you want to Delete this Agent?</h1>
	</div>
	<form method="POST">
		{% csrf_token %} {{ form|crispy }}
		<button
			class="
				w-full
				bg-blue-500
				text-white
				hover:bg-blue-600
				px-3
				py-2
				rounded-md
			"
			type="submit"
		>
			Create Lead
		</button>
	</form>
</div>

{% endblock content %}

agents/templates/agents/agentDetail.html
{% extends "base.html" %} {% block content %}

<section class="text-gray-600 body-font overflow-hidden">
	<div class="container px-5 py-24 mx-auto">
		<div class="lg:w-4/5 mx-auto flex flex-wrap">
			<div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
				<h2 class="text-sm title-font text-gray-500 tracking-widest">
					Agent
				</h2>
				<h1 class="text-gray-900 text-3xl title-font font-medium mb-4">
					{{agent.user.username}}
				</h1>
				<div class="flex mb-4">
					<a
						href="{% url 'agents:agentDetail' agent.pk %}"
						class="
							flex-grow
							text-indigo-500
							border-b-2 border-indigo-500
							py-2
							text-lg
							px-1
						"
						>Description</a
					>
					<a
						class="
							flex-grow
							border-b-2 border-gray-300
							py-2
							text-lg
							px-1
						"
						>Reviews</a
					>
					<a
						href="{% url 'agents:updateAgent' agent.pk %}"
						class="
							flex-grow
							border-b-2 border-gray-300
							py-2
							text-lg
							px-1
						"
						>Update Details</a
					>
				</div>
				<p class="leading-relaxed mb-4">
					Fam locavore kickstarter distillery. Mixtape chillwave
					tumeric sriracha taximy chia microdosing tilde DIY. XOXO fam
					inxigo juiceramps cornhole raw denim forage brooklyn.
					Everyday carry +1 seitan poutine tumeric. Gastropub blue
					bottle austin listicle pour-over, neutra jean.
				</p>
				<div class="flex border-t border-gray-200 py-2">
					<span class="text-gray-500">Age</span>
					<span class="ml-auto text-gray-900"></span>
				</div>
				<div class="flex border-t border-gray-200 py-2">
					<span class="text-gray-500">Location</span>
					<span class="ml-auto text-gray-900">Chandigarh</span>
				</div>
				<div class="flex border-t border-b mb-6 border-gray-200 py-2">
					<span class="text-gray-500">Phone Number</span>
					<span class="ml-auto text-gray-900">9796567567</span>
				</div>
				<div class="flex">
					<button
						class="
							flex
							ml-auto
							text-white
							bg-indigo-500
							border-0
							py-2
							px-6
							focus:outline-none
							hover:bg-indigo-600
							rounded
						"
					>
						Button
					</button>
					<button
						class="
							rounded-full
							w-10
							h-10
							bg-gray-200
							p-0
							border-0
							inline-flex
							items-center
							justify-center
							text-gray-500
							ml-4
						"
					>
						<svg
							fill="currentColor"
							stroke-linecap="round"
							stroke-linejoin="round"
							stroke-width="2"
							class="w-5 h-5"
							viewBox="0 0 24 24"
						>
							<path
								d="M20.84 4.61a5.5 5.5 0 00-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 00-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 000-7.78z"
							></path>
						</svg>
					</button>
				</div>
			</div>
			<img
				alt="ecommerce"
				class="
					lg:w-1/2
					w-full
					lg:h-auto
					h-64
					object-cover object-center
					rounded
				"
				src="https://dummyimage.com/400x400"
			/>
		</div>
	</div>
</section>

{% endblock content %}

agents/templates/agents/agentList.html
{% extends "base.html" %} {% block content %}
<section class="text-gray-600 body-font">
	<div class="container px-5 py-5 mx-auto flex flex-wrap">
		<div
			class="
				w-full
				mb-6
				py-3
				flex
				justify-between
				items-center
				border-b border-gray-200
			"
		>
			<div>
				<h1 class="text-4xl text-gray-800">Agents</h1>
			</div>
			<div>
				<a
					class="text-gray-500 hover:text-blue-500"
					href="{% url 'agents:createAgent' %}"
					>Create a New Agent</a
				>
			</div>
		</div>
		<div class="flex flex-wrap -m-4">
			{% for agent in object_list %}
			<div class="p-4 lg:w-1/2 md:w-full">
				<div
					class="
						flex
						border-2
						rounded-lg
						border-gray-200 border-opacity-50
						p-8
						sm:flex-row
						flex-col
					"
				>
					<div
						class="
							w-16
							h-16
							sm:mr-8
							sm:mb-0
							mb-4
							inline-flex
							items-center
							justify-center
							rounded-full
							bg-indigo-100
							text-indigo-500
							flex-shrink-0
						"
					>
						<svg
							fill="none"
							stroke="currentColor"
							stroke-linecap="round"
							stroke-linejoin="round"
							stroke-width="2"
							class="w-8 h-8"
							viewBox="0 0 24 24"
						>
							<path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
						</svg>
					</div>
					<div class="flex-grow">
						<h2
							class="
								text-gray-900 text-lg
								title-font
								font-medium
								mb-3
							"
						>
							{{ agent.user.username }}
						</h2>
						<p class="leading-relaxed text-base">
							Blue bottle crucifix vinyl post-ironic four dollar
							toast vegan taxidermy. Gastropub indxgo juice
							poutine.
						</p>
						<a
							href="{% url 'agents:agentDetail' agent.pk %}"
							class="
								mt-3
								text-indigo-500
								inline-flex
								items-center
							"
						>
							View Agent
							<svg
								fill="none"
								stroke="currentColor"
								stroke-linecap="round"
								stroke-linejoin="round"
								stroke-width="2"
								class="w-4 h-4 ml-2"
								viewBox="0 0 24 24"
							>
								<path d="M5 12h14M12 5l7 7-7 7"></path>
							</svg>
						</a>
					</div>
				</div>
			</div>
			{% empty %}
			<p>There are currently no leads</p>

			{% endfor %}
		</div>
	</div>
</section>

{% endblock content %}

agents/templates/agents/createAgent.html
{% extends "base.html" %} {% load tailwind_filters %} {% block content %}

<div class="max-w-lg mx-auto">
	<div class="pt-3 border-b border-gray-300 mt-2 mb-4 pb-2">
		<a class="hover:text-blue-500" href="{% url 'agents:agentList' %}"
			>Go Back to Agents</a
		>
	</div>
	<form method="POST">
		{% csrf_token %} {{ form|crispy }}
		<button
			class="
				w-full
				bg-blue-500
				text-white
				hover:bg-blue-600
				px-3
				py-2
				rounded-md
			"
			type="submit"
		>
			Create Agent
		</button>
	</form>
</div>

{% endblock content %}

agents/templates/agents/updateAgent.html
{% extends "base.html" %} {% load tailwind_filters %} {% block content %}

<section class="text-gray-600 body-font overflow-hidden">
	<div class="container px-5 py-12 mx-auto">
		<div class="lg:w-4/5 mx-auto flex flex-wrap">
			<div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
				<h2 class="text-sm title-font text-gray-500 tracking-widest">
					Agent
				</h2>
				<h1 class="text-gray-900 text-3xl title-font font-medium mb-4">
					{{ agent.user.username }}
				</h1>
				<div class="flex mb-4">
					<a
						href="{% url 'agents:agentDetail' agent.pk %}"
						class="
							flex-grow
							border-b-2 border-gray-300
							py-2
							text-lg
							px-1
						"
						>Description</a
					>
					<a
						class="
							flex-grow
							border-b-2 border-gray-300
							py-2
							text-lg
							px-1
						"
						>Reviews</a
					>
					<a
						href="{% url 'agents:updateAgent' agent.pk %}"
						class="
							flex-grow
							text-indigo-500
							border-b-2 border-indigo-500
							py-2
							text-lg
							px-1
						"
						>Update Details</a
					>
				</div>
				<form action="." method="POST">
					{% csrf_token %} {{ form|crispy}}
					<button
						class="
							w-full
							bg-blue-500
							text-white
							hover:bg-blue-600
							px-3
							py-2
							rounded-md
						"
						type="submit"
					>
						Update Details
					</button>
				</form>
				<div class="mt-5 py-5 border-t border-gray-200">
					<a
						href="{% url 'agents:deleteAgent' agent.pk %}"
						class="
							w-1/2
							mt-3
							text-white
							bg-indigo-500
							border-0
							py-2
							px-6
							focus:outline-none
							hover:bg-indigo-600
							rounded
						"
					>
						Delete Lead
					</a>
				</div>
			</div>
			<img
				alt="ecommerce"
				class="
					lg:w-1/2
					w-full
					lg:h-auto
					h-64
					object-cover object-center
					rounded
				"
				src="https://dummyimage.com/400x400"
			/>
		</div>
	</div>
</section>

{% endblock content %}